<?php

# COMERICA

$DOPPLER_PAYMENTS_API_URL = getenv('DOPPLER_PAYMENTS_API_URL') ?: '';
$DOPPLER_PAYMENTS_API_STATIC_BEARER_TOKEN = getenv('DOPPLER_PAYMENTS_API_STATIC_BEARER_TOKEN') ?: '';
$DOPPLER_PAYMENTS_API_AUTH_MODE = getenv('DOPPLER_PAYMENTS_API_AUTH_MODE') ?: 'jwt_superuser';
$DOPPLER_PAYMENTS_API_PRIVATE_KEY_FILE = getenv('DOPPLER_PAYMENTS_API_PRIVATE_KEY_FILE') ?: '';
$DOPPLER_PAYMENTS_API_PRIVATE_KEY = getenv('DOPPLER_PAYMENTS_API_PRIVATE_KEY') ?: '';
$DOPPLER_PAYMENTS_API_JWT_AUDIENCE = getenv('DOPPLER_PAYMENTS_API_JWT_AUDIENCE') ?: 'doppler-payments-api';
$DOPPLER_PAYMENTS_API_JWT_ISSUER = getenv('DOPPLER_PAYMENTS_API_JWT_ISSUER') ?: '';
$DOPPLER_PAYMENTS_API_CONNECT_TIMEOUT_SECONDS = getenv('DOPPLER_PAYMENTS_API_CONNECT_TIMEOUT_SECONDS') ?: 5;
$DOPPLER_PAYMENTS_API_TIMEOUT_SECONDS = getenv('DOPPLER_PAYMENTS_API_TIMEOUT_SECONDS') ?: 30;
$EPROTECT_SCRIPT_URL = getenv('EPROTECT_SCRIPT_URL') ?: '';
$EPROTECT_PAYPAGE_ID = getenv('EPROTECT_PAYPAGE_ID') ?: '';
$EPROTECT_REPORT_GROUP = getenv('EPROTECT_REPORT_GROUP') ?: '';
$EPROTECT_STYLE = getenv('EPROTECT_STYLE') ?: '';
$EPROTECT_TIMEOUT_MS = getenv('EPROTECT_TIMEOUT_MS') ?: 5000;

if (!defined('DOPPLER_PAYMENTS_API_URL')) define('DOPPLER_PAYMENTS_API_URL', rtrim((string) $DOPPLER_PAYMENTS_API_URL, '/'));
if (!defined('DOPPLER_PAYMENTS_API_STATIC_BEARER_TOKEN')) define('DOPPLER_PAYMENTS_API_STATIC_BEARER_TOKEN', (string) $DOPPLER_PAYMENTS_API_STATIC_BEARER_TOKEN);
if (!defined('DOPPLER_PAYMENTS_API_AUTH_MODE')) define('DOPPLER_PAYMENTS_API_AUTH_MODE', (string) $DOPPLER_PAYMENTS_API_AUTH_MODE);
if (!defined('DOPPLER_PAYMENTS_API_PRIVATE_KEY_FILE')) define('DOPPLER_PAYMENTS_API_PRIVATE_KEY_FILE', (string) $DOPPLER_PAYMENTS_API_PRIVATE_KEY_FILE);
if (!defined('DOPPLER_PAYMENTS_API_PRIVATE_KEY')) define('DOPPLER_PAYMENTS_API_PRIVATE_KEY', (string) $DOPPLER_PAYMENTS_API_PRIVATE_KEY);
if (!defined('DOPPLER_PAYMENTS_API_JWT_AUDIENCE')) define('DOPPLER_PAYMENTS_API_JWT_AUDIENCE', (string) $DOPPLER_PAYMENTS_API_JWT_AUDIENCE);
if (!defined('DOPPLER_PAYMENTS_API_JWT_ISSUER')) define('DOPPLER_PAYMENTS_API_JWT_ISSUER', (string) $DOPPLER_PAYMENTS_API_JWT_ISSUER);
if (!defined('DOPPLER_PAYMENTS_API_CONNECT_TIMEOUT_SECONDS')) define('DOPPLER_PAYMENTS_API_CONNECT_TIMEOUT_SECONDS', (int) $DOPPLER_PAYMENTS_API_CONNECT_TIMEOUT_SECONDS);
if (!defined('DOPPLER_PAYMENTS_API_TIMEOUT_SECONDS')) define('DOPPLER_PAYMENTS_API_TIMEOUT_SECONDS', (int) $DOPPLER_PAYMENTS_API_TIMEOUT_SECONDS);
if (!defined('EPROTECT_SCRIPT_URL')) define('EPROTECT_SCRIPT_URL', (string) $EPROTECT_SCRIPT_URL);
if (!defined('EPROTECT_PAYPAGE_ID')) define('EPROTECT_PAYPAGE_ID', (string) $EPROTECT_PAYPAGE_ID);
if (!defined('EPROTECT_REPORT_GROUP')) define('EPROTECT_REPORT_GROUP', (string) $EPROTECT_REPORT_GROUP);
if (!defined('EPROTECT_STYLE')) define('EPROTECT_STYLE', (string) $EPROTECT_STYLE);
if (!defined('EPROTECT_TIMEOUT_MS')) define('EPROTECT_TIMEOUT_MS', (int) $EPROTECT_TIMEOUT_MS);
